### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by bmf-san**
# Description
For releasing 1.0.0.

# Todo
- [x] Rename repository name, sea-css  to  sea.css
- [x] Determine the directory structure
- [x] Determine the structure of the document
- [x] Planning for coding the design
- [x] Create a logo
- [x] Setup base & component
- [x] Prepare PostCSS
- [x] Create example pages.
- [x] Determine the design concept, and write the description of this repository
- [ ] Coding the design
- [ ] Write a README.
- [ ] Show a document page by github pages

# Setup
- [x] base
  - [x] _element
  - [x] _container
- [x] component
  - [x]  _alert
  - [x] _footer
  - [x] _form
  - [x] _header
  - [x] _media
  - [x] _pagination
  - [x] _tag
- [ ] utils
  - [ ] _color
  - [ ] _size
  - [ ] _spacing 

# Design
- [x] base
  - [x] _element
  - [x] _container
- [x] component
  - [x] _alert
  - [x] _footer
  - [x] _form
  - [x] _header
  - [x] _media
  - [x] _pagination 
  - [x] _tag
- [ ] utils
  - [ ] _color
  - [ ] _size
  - [ ] _spacing 

# References
- https://www.invisionapp.com/inside-design/equity-design-covid-19/
- https://www.helpscout.com/blog/customer-survey/
- https://www.thoughtworks.com/insights/blog/stories-social-change-protecting-front-line-workers-during-covid-19-technology
- https://getwaves.io/
- https://www.it-swarm.dev/ja/autocomplete/chrome%E3%82%AA%E3%83%BC%E3%83%88%E3%82%B3%E3%83%B3%E3%83%97%E3%83%AA%E3%83%BC%E3%83%88%E3%81%AE%E5%85%A5%E5%8A%9B%E8%83%8C%E6%99%AF%E8%89%B2%E3%82%92%E5%89%8A%E9%99%A4%E3%81%97%E3%81%BE%E3%81%99%E3%81%8B%EF%BC%9F/970056705/
- https://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete

# memo
@amf-san 
- [ ] aタグ、ボタン等のhoverの色をsubmitと同じにする
- [ ] tagのhoverの色調整→paginationと同じ
- [ ] listページのデザイン
- [ ] 各ページのcontainerのmax-widthをベタ書き調整

### CODE REVIEW

**Comment by amf-san** [comment]
アセット 3@3x

**Comment by bmf-san** [comment]
https://www.it-swarm.dev/ja/autocomplete/chrome%E3%82%AA%E3%83%BC%E3%83%88%E3%82%B3%E3%83%B3%E3%83%97%E3%83%AA%E3%83%BC%E3%83%88%E3%81%AE%E5%85%A5%E5%8A%9B%E8%83%8C%E6%99%AF%E8%89%B2%E3%82%92%E5%89%8A%E9%99%A4%E3%81%97%E3%81%BE%E3%81%99%E3%81%8B%EF%BC%9F/970056705/

**Comment by bmf-san** [comment]
https://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete

**Comment by bmf-san** [comment]
```js
{
    "name": "sea.css",
    "version": "1.0.0",
    "description": "sea.css is a simple and easy to use css framework.",
    "main": "dist/sea.min.css",
    "directories": {
        "doc": "docs"
    },
    "dependencies": {
        "stylelint": "^13.5.0"
    },
    "devDependencies": {
        "autoprefixer": "^9.8.0",
        "cross-env": "^7.0.2",
        "cssnano": "^4.1.10",
        "npm-run-all": "^4.1.5",
        "postcss-cli": "^7.1.1",
        "postcss-csso": "^4.0.0",
        "postcss-import": "^12.0.1",
        "postcss-sorting": "^5.0.1",
        "rimraf": "^3.0.2",
        "stylelint-order": "^4.0.0"
    },
    "files": [
        "src/",
        "dist/",
        "README.md"
    ],
    "scripts": {
        "build": "rimraf dist/* && npm-run-all postcss && cross-env NODE_ENV=production postcss ./src/sea.css --ext .min.css --dir=dist/ && gzip -c dist/sea.min.css | wc -c | xargs echo 'Size:'",
        "postcss": "postcss ./src/sea.css -d dist/",
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [
        "css",
        "simple",
        "minimal",
        "postcss"
    ],
    "repository": {
        "type": "git",
        "url": "git+https://github.com/bmf-san/sea.css.git"
    },
    "author": "bmf-san",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/bmf-san/sea.css/issues"
    },
    "homepage": "https://github.com/bmf-san/sea.css#readme"
}

```

**Comment by bmf-san** [comment]
closed.
rename branch name.
https://github.com/bmf-san/sea.css/pull/4

**Pull request closed without merging**
